---
- name: Setup Bastion Host
  hosts: bastion
  gather_facts: no
  tasks:
    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: 86400
      loop:
        - git
        - ansible
        - python3-boto3
        - python3-botocore
        - python3-boto
      tags:
        - package

    - file:
        path: ansible_project
        state: directory
      register: dir_status

    - name: Clone source code from github
      git:
        repo: 'https://github.com/thczzz/ansible_project.git'
        dest: ./ansible_project
        version: master
      when: dir_status.changed
      register: git_out

    - name: Copy key to bastion
      copy:
        src: ./loginkey_vpro.pem
        dest: ansible_project/provision_stack/loginkey_vpro.pem
        mode: 0400
      when: git_out.changed

    - name: Copy inventory-vpro to bastion
      copy:
        src: provision_stack/inventory-vpro
        dest: ansible_project/provision_stack/inventory-vpro
        force: true
      when: git_out.changed

    - name: Copy hostsip to bastion
      copy:
        src: provision_stack/group_vars/hostsip
        dest: ansible_project/provision_stack/group_vars/hostsip
        force: true
      when: git_out.changed
