---
- name: Setup Vprofile stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variables
      ansible.builtin.include_vars: vars/vpc_output_vars

    - name: Import vprofile setup variables
      ansible.builtin.include_vars: vars/vprostack_setup
        
    - name: Create vprofile ec2 key
      ec2_key:
        name: vprokey
        region: "{{ region }}"
      register: vprokey_out

    - name: Stave private key into file loginkey_vpro.pem
      copy:
        content: "{{ vprokey_out.key.private_key }}"
        dest: ./loginkey_vpro.pem
        mode: 0600
      when: vprokey_out.changed

    - name: Create Security Group for Load Balancer
      amazon.aws.ec2_group:
        name: vproELB-SG
        description: Allow port 80 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: vproELBSG_out

    - name: Create Security Group for Vprofile Stack
      amazon.aws.ec2_group:
        name: vproStack-SG
        description: Allow
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{ vproELBSG_out.group_id }}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{ BastionSGid }}"
      register: vproStackSG_out
    
    - name: Update vproStack-SG
      amazon.aws.ec2_group:
        name: vproStack-SG
        description: Allow traffic on all ports from its own SG
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{ vproStackSG_out.group_id }}"

    - name: Create Nginx web01
      amazon.aws.ec2_instance:
        key_name: vprokey
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ nginx_ami }}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: "web01"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1
        security_group: "{{ vproStackSG_out.group_id }}"
        vpc_subnet_id: "{{ privsub1_id }}"
      register: web01_out

    - name: Create Tomcat app01
      amazon.aws.ec2_instance:
        key_name: vprokey
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ tomcat_ami }}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: "app01"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1
        security_group: "{{ vproStackSG_out.group_id }}"
        vpc_subnet_id: "{{ privsub1_id }}"
      register: app01_out

    - name: Create memcahed mc01
      amazon.aws.ec2_instance:
        key_name: vprokey
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ memcached_ami }}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: "mc01"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1
        security_group: "{{ vproStackSG_out.group_id }}"
        vpc_subnet_id: "{{ privsub1_id }}"
      register: mc01_out

    - name: Create RabbitMq rmq01
      amazon.aws.ec2_instance:
        key_name: vprokey
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ rmq_ami }}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: "rmq01"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1
        security_group: "{{ vproStackSG_out.group_id }}"
        vpc_subnet_id: "{{ privsub1_id }}"
      register: rmq01_out

    - name: Create MySql db01
      amazon.aws.ec2_instance:
        key_name: vprokey
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ mysql_ami }}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: "db01"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1
        security_group: "{{ vproStackSG_out.group_id }}"
        vpc_subnet_id: "{{ privsub1_id }}"
      register: db01_out

    - name: List all EC2 instances
      ec2_instance_info:
        filters:
          "tag:Name": web01
          "tag:Name": app01
          "tag:Name": rmq01
          "tag:Name": mc01
          "tag:Name": db01
      register: instances_out

    # - debug:
    #     var: result

    - name: Create ELB
      local_action:
        module: ec2_elb_lb
        name: "vprofile-elb"
        region: "{{ region }}"
        state: present
        instance_ids:
          - "{{ instances_out.instances[0].instance_id }}"
        purge_instance_ids: true
        security_group_ids: ["{{ vproELBSG_out.group_id }}"]
        subnets:
          - "{{ pubsub1_id }}"
          - "{{ pubsub2_id }}"
          - "{{ pubsub3_id }}"
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80

    - name: Add Hosts IPs & Name in file provision_stack/group_vars/hostsip
      ansible.builtin.blockinfile:
        path: provision_stack/group_vars/hostsip
        block: |
          web01_ip: {{ instances_out.instances[0].instance_id }}
          app01_ip: {{ instances_out.instances[1].instance_id }}
          rmq01_ip: {{ instances_out.instances[2].instance_id }}
          mc01_ip:  {{ instances_out.instances[3].instance_id }}
          db01_ip:  {{ instances_out.instances[4].instance_id }}
    
    - name: Copy login key to provision_stack dir
      ansible.builtin.copy:
        src: loginkey_vpro.pem
        dest: provision_stack/loginkey_vpro.pem
        mode: '0400'
    
    - name: Add Inventory file provision_stack/inventory-vpro
      ansible.builtin.blockinfile:
        path: provision_stack/inventory-vpro
        block: |
          web01 ansible_host={{ instances_out.instances[0].instance_id }}
          app01 ansible_host={{ instances_out.instances[1].instance_id }}
          rmq01 ansible_host={{ instances_out.instances[2].instance_id }}
          mc01_ip ansible_host={{ instances_out.instances[3].instance_id }}
          db01_ip ansible_host={{ instances_out.instances[4].instance_id }}
          cntl ansible_host=127.0.0.1 ansible_connection=local

          [websrvgrp]
          web01

          [appsrvgrp]
          app01

          [rmqsrvgrp]
          rmq01

          [mcsrvgrp]
          mc01

          [dbsrvgrp]
          db01

          [control]
          cntl

          [stack_inst:children]
          websrvgrp
          appsrvgrp
          rmqsrvgrp
          mcsrvgrp
          dbsrvgrp

          [stack_inst:vars]
          ansible_user=ubuntu
          ansible_ssh_private_key_file=loginkey_vpro.pem
          #ansible_python_interpreter=/usr/bin/python3
