- name: Generate artifact, copy artifact & sql file to files directory
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: uninstall jdk 11
      apt:
        name: openjdk-11-jdk
        state: absent
        update_cache: yes

    - name: Install jdk, maven, git
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - git
        - openjdk-8-jdk
        - maven

    - file:
        path: ansible_project/provision_stack/Vprofile-repo
        state: directory
      register: vprofile_out

    - name: Clone source code from github
      git:
        repo: 'https://github.com/devopshydclub/vprofile-project.git'
        dest: ./Vprofile-repo
        version: vp-rem
      when: vprofile_out.changed
      register: git_status

    - name: mvn install command to build artifact
      command: "mvn install"
      args:
        chdir: Vprofile-repo
      when: git_status.changed
      register: mvn_info

    - name: Copy artifacts to files directory
      copy:
        src: "{{ item }}"
        dest: files/ROOT.war
      with_fileglob: Vprofile-repo/target/*.war
    
    - name: Copy SQL file to files directory
      copy:
        src: "Vprofile-repo/src/main/resources/db_backup.sql"
        dest: files/db_backup.sql

