---
- name: Deploy SQL file on accounts DB
  hosts: dbsrvgrp
  gather_facts: no
  tasks:
    - name: Copy sql file to dbsrv
      ansible.builtin.copy:
        src: files/db_backup.sql
        dest: /tmp/db_backup.sql
      tags:
        - deploy

    - name: Restoring DB
      ansible.builtin.mysql_db:
        name: accounts
        login_user: "{{ dbuser }}"
        login_password: "{{ dbpass }}"
        state: import
        target: /tmp/db_backup.sql
      notify:
        - Restart mysql
      tags:
        - deploy
        