---
- name: Deploy SQL file on accounts DB
  hosts: dbsrvgrp
  gather_facts: no
  tasks:
    - name: Copy sql file to dbsrv
      copy:
        src: files/db_backup.sql
        dest: /tmp/db_backup.sql
        force: false
      tags:
        - deploy
      register: backup_out

    - name: Restoring DB
      mysql_db:
        name: accounts
        login_user: "{{ dbuser }}"
        login_password: "{{ dbpass }}"
        state: import
        target: /tmp/db_backup.sql
      notify:
        - Restart mysql
      tags:
        - deploy
      when: backup_out.changed

  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted
