---
- name: Install & Setup RabbitMq with user
  hosts: rmqsrvgrp
  gather_facts: no

  tasks:
    - name: Check if erlang is installed
      command: dpkg-query -l erlang
      register: erlang_check
      ignore_errors: true

    - name: Install erlang on ubuntu 20.04
      shell: |
        sudo apt update
        sudo apt install curl software-properties-common apt-transport-https lsb-release -y
        curl -fsSL https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/erlang.gpg
        echo "deb https://packages.erlang-solutions.com/ubuntu $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/erlang.list
        sudo apt update
        sudo apt install erlang -y
      when: erlang_check is failed

    - name: Check if rabbitmq is installed
      command: dpkg-query -l rabbitmq-server
      register: rabbitmq_check
      ignore_errors: true

    - name: Install RabbitMq
      shell: |
        curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | sudo bash
        sudo apt update
        sudo apt install rabbitmq-server -y
      register: rabbitmq_out
      when: rabbitmq_check is failed

    - name: Start & Enable RMQ
      service:
        name: rabbitmq-server
        state: started
        enabled: yes
      tags:
        - svc

    - name: Config setup
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify:
        - Restart RMQ
      tags:
        - conf

    - rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify:
        - Restart RMQ
      tags:
        - conf
      when: rabbitmq_out.changed

    - name: Enable the rabbitmq_management plugin
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - Restart RMQ
      tags:
        - package
      when: rabbitmq_out.changed

  handlers:
    - name: Restart RMQ
      service:
        name: rabbitmq-server
        state: restarted
