---
- name: Build Artifact ROOT.war & SQL file to be copied in files/ directory
  ansible.builtin.import_playbook: build.yaml

- name: Set Hosts to IP Mapping in /etc/hosts file of all servers
  ansible.builtin.import_playbook: set_host_ip_map.yaml

- name: Setup DB server
  ansible.builtin.import_playbook: db.yaml

- name: Deploy SQL file on Dbserver
  ansible.builtin.import_playbook: dbdeploy.yaml

- name: Setup Memcached service
  ansible.builtin.import_playbook: memcached.yaml

- name: Setup RabbitMq service
  ansible.builtin.import_playbook: rabbitmq.yaml

- name: Setup Tomcat application server
  ansible.builtin.import_playbook: appserver.yaml

- name: Setup Nginx webserver
  ansible.builtin.import_playbook: web.yaml
