---
# Build Artifact ROOT.war & SQL file to be copied in files/ directory
- import_playbook: build.yaml

# Set Hosts to IP Mapping in /etc/hosts file of all servers
- import_playbook: set_host_ip_map.yaml

# Setup DB server
- import_playbook: db.yaml

# Deploy SQL file on Dbserver
- import_playbook: dbdeploy.yaml

# Setup Memcached service
- import_playbook: memcached.yaml

# Setup RabbitMq service
- import_playbook: rabbitmq.yaml

# Setup Tomcat application server
- import_playbook: appserver.yaml

# Setup Nginx webserver
- import_playbook: web.yaml
